Add configurable blacklist time for many checks util
Leymooo/BungeeCord pull request #122
Opened 2022-07-09 10:52 UTC by xIsm4

2022-07-09 14:31 UTC, xIsm4 commented
> Remove this, it is already done by BungeeCord and will be added together with upstream

You mean http handler?

2022-07-09 14:33 UTC, xIsm4 commented
K, already did

2022-07-11 15:47 UTC, NoJokeFNA requested changes

2022-07-11 15:47 UTC, NoJokeFNA commented on proxy/src/main/java/ru/leymooo/botfilter/config/Settings.java
> +    public boolean SHOW_ONLINE = false;
```suggestion
    public boolean SHOW_ONLINE = true;
```
Please do this in another Pull-Request as it is something complete different.

2022-07-11 15:47 UTC, NoJokeFNA commented on proxy/src/main/java/ru/leymooo/botfilter/config/Settings.java
> +        @Comment("Как долго вы хотите, чтобы черный список был для игрока")
You should probably say that the time is in minutes

2022-07-11 21:26 UTC, xIsm4 commented on proxy/src/main/java/ru/leymooo/botfilter/config/Settings.java
> +        @Comment("Как долго вы хотите, чтобы черный список был для игрока")
> You should probably say that the time is in minutes

Well, my russian is translator basicly but k

2022-07-11 21:38 UTC, NoJokeFNA approved these changes
Looks good to me in general

2022-08-27 08:13 UTC, closed without merging